### ISSUE TITLE
Slappers

### ISSUE THREAD

**Issue by SkyNetServer** [TheWalker0/MobStacker#1]
Doesn't works with slapper.
Try adding this:
if($entity instanceof Living && !($entity instanceof Player) && !($entity instanceof SlapperEntity))

**Comment by moch09** [comment]
Install where? Stack factory?

**Comment by RubyTemple** [comment]
Monday I will fix the bug

**Comment by RubyTemple** [comment]
If you want to help me open a pull request

**Comment by RubyTemple** [comment]
i have fix
