### ISSUE TITLE
[FIXED]Stack Slappers

### ISSUE THREAD

**Issue by MrNoob6969** [TheWalker0/MobStacker#2]
It stack up slappers as well. Make it so it doesn't stack up slappers.

**Comment by RubyTemple** [comment]
Ok, Monday I will fix the bug

**Comment by RubyTemple** [comment]
i have fix

**Comment by Danjoe3** [comment]
Hey there TheWalker0 would it be possible for you to update the fix on poggit if possible? :)
Thank you :smile:

**Comment by RubyTemple** [comment]
What problem?

**Comment by Danjoe3** [comment]
The slapper and stacker link issue? Cuz the Dev 4 build on poggit, still has the same issue. Maybe we can discuss this through discord?

**Comment by RubyTemple** [comment]
Are slappers still stacked? REALLY?

**Comment by Danjoe3** [comment]
Yes, they still do. :(

**Comment by RubyTemple** [comment]
Now check and try to resolve, sorry for the inconvenience.

**Comment by RubyTemple** [comment]
update plugin to latest version, i have fix slapper bug

**Comment by RubyTemple** [comment]
is all ok? is all working?
