### ISSUE TITLE
Someone is stoling your plugin!

### ISSUE THREAD

**Issue by LeoBdt** [TheWalker0/MobStacker#3]
https://github.com/RaccoonUndercover/Mobstacker

It's exacly the same code.

**Comment by RaccoonUndercover** [comment]
Mine has a License

**Comment by RaccoonUndercover** [comment]
and you copied it from someone else

**Comment by LeoBdt** [comment]
But it's exacly the same code.

**Comment by LeoBdt** [comment]
And you copied it too. ridiculous.

**Comment by RubyTemple** [comment]
pls stop flame and stop copy my plugin thanks
