### ISSUE TITLE
Suggestion ~ Mob stack limits

### ISSUE THREAD

**Issue by Xenophilicy** [TheWalker0/MobStacker#4]
@TheWalker0 Hello, great plugin first of all. Just wanted to suggest one thing my players were requesting of me. Could you add a function to limit how many mobs can be added per stack? Say for instance the mob stack gets to 16 and you set that as the limit, it would then create a new stack on the nearest mob and keep repeating this process over and over.

 It would also be beneficial to add a way to remove all stacked mobs, maybe with a command such as `/killstacks`. This can help reduce some lag if the command was on a timer to run every 3 days or so on a big SkyBlock server.

Just some ideas, no pressure in adding them. Hope you consider! Thanks!

**Comment by RubyTemple** [comment]
regarding / killstacks just use a simple clearlagg, because of the decision of how many mobs stack, I can not, this plugin was born to reduce the lag and then I do not see the usefulness

**Comment by Xenophilicy** [comment]
@TheWalker0 is that English? I didn't understand any of that. Make some logical sentences please. Lol

Also this can very easily be achieved by checking the stack value and then getting an element from the config to set a max stack value. Once it reached that stack number create a new stack or add to the nearest stack of that same type.

**Comment by RubyTemple** [comment]
The plugin was created to reduce lag. while to remove the stack just use a simple clearlagg

**Comment by Xenophilicy** [comment]
That's not what I'm requesting, I don't want the stack to be removed as that's the player's job in game. I just want to set a limit to how high the stack goes, right now it just goes to infinity. I'd like to be able to stop the stack at 25 entities and then once that's reached, create a new stack. Please explain to me why this cannot just be an optional add-on you implement for me.

**Comment by RubyTemple** [comment]
as I said the plugin was created to minimize the lag caused by the enities in the server.

**Comment by Xenophilicy** [comment]
Ok, I'm just trying to help the plugin out dude. I've had two server owners come to me asking to edit this exact plugin to add this feature. I will just add it myself. Thanks for you let help. Have a good day 👍

**Comment by RubyTemple** [comment]
unfortunately I do not have time for a rewrite of the code for your changes but if you want to do so I can post and give you the credits
