### ISSUE TITLE
Enhancement - Set mobs to 1 hit kill

### ISSUE THREAD

**Issue by ver24436** [TheWalker0/MobStacker#5]
Hi, just wanted to know if there is a simple way to make it so any mobs in the stack can be 1 hit 1 kill?

Thanks for providing this free public plugin. It's very useful.

**Comment by RubyTemple** [comment]
Ok I will implement this

**Comment by RubyTemple** [comment]
can you explain what you want implemented?

**Comment by mikeygio10** [comment]
Just get a sharp 5 sword or something higher

**Comment by RubyTemple** [comment]
Yes this is true..

**Comment by ver24436** [comment]
The option to set it so any mob in the stack is one hit kill even with just  your fist.

I tried to do this myself by  adding $entity->setHealth(1);  onSpawn 
but every time i tap a mob 2 are killed.

**Comment by RubyTemple** [comment]
Ok

**Comment by LeoBdt** [comment]
Any news?

**Comment by ver24436** [comment]
> Any news?

Nope, but found another plugin that does what I needed.

**Comment by LeoBdt** [comment]
link please?

**Comment by thewalker0** [comment]
tomorrow i will update this pl
